import fs from 'node:fs';
import path from 'node:path';

const moviesDir = path.resolve('src/content/movies');

const moviesData = [
  {
    title: 'The Fantastic Four: First Steps',
    slug: 'fantastic-four-first-steps',
    description: 'Set against the vibrant backdrop of a 1960s-inspired retro-futuristic world, Marvel\'s First Family must balance their familial bonds with defending Earth from the cosmic threat of Galactus and the Silver Surfer.',
    status: 'IN_PRODUCTION',
    releaseDate: 'July 25, 2025',
    heroImage: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?q=80&w=1600&auto=format&fit=crop',
    heroImageAlt: 'Retro-futuristic skyline of New York City dominated by the iconic Baxter Building rocket spire',
    poster: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?q=80&w=600&auto=format&fit=crop',
    genres: ['Sci-Fi', 'Adventure', 'Action'],
    tags: ['Fantastic Four', 'Baxter Building', 'Galactus', '1960s', 'Phase 6'],
    characters: ['mr-fantastic', 'invisible-woman', 'human-torch', 'the-thing', 'galactus', 'silver-surfer', 'doctor-doom'],
    actors: ['Pedro Pascal', 'Vanessa Kirby', 'Joseph Quinn', 'Ebon Moss-Bachrach', 'Ralph Ineson', 'Julia Garner'],
    featured: true,
    director: 'Matt Shakman',
    writers: ['Josh Friedman', 'Jeff Kaplan', 'Ian Springer', 'Eric Pearson'],
    producers: ['Kevin Feige'],
    universe: 'Earth-Retro 1960s / Earth-616',
    timeline: 'Phase 6 Kickoff',
    synopsis: 'In an alternate 1960s reality where space-age technological optimism reigns supreme, scientific pioneers Reed Richards, Sue Storm, Johnny Storm, and Ben Grimm navigate their newfound cosmic mutations while confronting the impending arrival of the world-devourer Galactus.',
    officialSources: [
      { name: 'Marvel.com', url: 'https://www.marvel.com/movies/the-fantastic-four-first-steps' },
      { name: 'Variety', url: 'https://variety.com/2024/film/news/fantastic-four-cast-pedro-pascal-vanessa-kirby-1235910398/' }
    ],
    seoTitle: 'The Fantastic Four: First Steps | Cast, Release Date & Marvel News',
    seoDescription: 'Complete intelligence dossier on Marvel Studios\' The Fantastic Four: First Steps, starring Pedro Pascal, Vanessa Kirby, Joseph Quinn, and Ebon Moss-Bachrach.'
  },
  {
    title: 'Spider-Man: Brand New Day',
    slug: 'spiderman-brand-new-day',
    description: 'Stripped of Stark technology and forgotten by everyone he loved, Peter Parker navigates the dangerous criminal syndicates of New York City in a grounded, street-level war for the soul of Manhattan.',
    status: 'PRE_PRODUCTION',
    releaseDate: 'July 10, 2026',
    heroImage: 'https://images.unsplash.com/photo-1635805737707-575885ab0820?q=80&w=1600&auto=format&fit=crop',
    heroImageAlt: 'Spider-Man crouching atop a rain-slicked Manhattan water tower overlooking illuminated Midtown avenue',
    poster: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=600&auto=format&fit=crop',
    genres: ['Action', 'Crime', 'Sci-Fi'],
    tags: ['Spider-Man', 'Street Level', 'Tombstone', 'Daredevil', 'NYC Underworld'],
    characters: ['spider-man', 'daredevil', 'punisher', 'scorpion', 'tombstone'],
    actors: ['Tom Holland', 'Zendaya', 'Charlie Cox', 'Jon Bernthal', 'Michael Mando'],
    featured: true,
    director: 'Destin Daniel Cretton',
    writers: ['Chris McKenna', 'Erik Sommers'],
    producers: ['Kevin Feige', 'Amy Pascal'],
    universe: 'Earth-616',
    timeline: 'Post-No Way Home / Pre-Doomsday',
    synopsis: 'Following the total erasure of his identity from the world\'s memory, Peter Parker embarks on his college years at Empire State University. When a violent syndicate war ignites between Tombstone and rival underworld factions across the five boroughs, Peter must rely strictly on his wits, instincts, and classic cloth webbing.',
    officialSources: [
      { name: 'Marvel Studios / Sony Pictures', url: 'https://www.marvel.com/movies' },
      { name: 'The Hollywood Reporter', url: 'https://www.hollywoodreporter.com/movies/movie-news/spider-man-4-destin-daniel-cretton-1235996025/' }
    ],
    seoTitle: 'Spider-Man: Brand New Day | Cast, Release Date & NYC Leaks',
    seoDescription: 'Latest news, rumors, leaks, and production updates on Tom Holland\'s Spider-Man: Brand New Day directed by Destin Daniel Cretton.'
  },
  {
    title: 'Avengers: Doomsday',
    slug: 'avengers-doomsday',
    description: 'Victor Von Doom emerges as an unprecedented planetary-level threat, confronting a newly reformed Avengers roster across international and extra-dimensional battlegrounds.',
    status: 'PRE_PRODUCTION',
    releaseDate: 'May 1, 2026',
    heroImage: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?q=80&w=1600&auto=format&fit=crop',
    heroImageAlt: 'Stark mountain cliffs and glacial waters shrouded in mist surrounding Castle Doom',
    poster: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=600&auto=format&fit=crop',
    genres: ['Action', 'Sci-Fi', 'Drama'],
    tags: ['Avengers', 'Doctor Doom', 'Latveria', 'Phase 6', 'Multiverse Saga'],
    characters: ['doctor-doom', 'mr-fantastic', 'invisible-woman', 'human-torch', 'the-thing', 'spider-man', 'thor', 'captain-america-sam-wilson', 'hulk', 'doctor-strange', 'yelena-belova', 'bucky-barnes', 'shang-chi', 'wolverine'],
    actors: ['Robert Downey Jr.', 'Pedro Pascal', 'Vanessa Kirby', 'Joseph Quinn', 'Ebon Moss-Bachrach', 'Tom Holland', 'Chris Hemsworth', 'Anthony Mackie', 'Mark Ruffalo', 'Benedict Cumberbatch', 'Florence Pugh', 'Sebastian Stan'],
    featured: true,
    director: 'Anthony Russo & Joe Russo',
    writers: ['Stephen McFeely'],
    producers: ['Kevin Feige', 'Anthony Russo', 'Joe Russo'],
    universe: 'Earth-616 / Multiverse',
    timeline: 'Phase 6 Climax Event Part 1',
    synopsis: 'As the boundaries between realities begin collapsing into destructive incursions, sovereign despot Victor von Doom unveils a terrifying cosmic design to subjugate all remaining timelines. Sam Wilson, Thor, and the Fantastic Four must assemble a fractured alliance of Earth-616 and multiverse heroes before reality dissolves completely.',
    officialSources: [
      { name: 'Marvel.com Hall H Reveal', url: 'https://www.marvel.com/articles/movies/sdcc-2024-avengers-doomsday-secret-wars-russo-brothers-robert-downey-jr' },
      { name: 'Deadline', url: 'https://deadline.com/2024/07/robert-downey-jr-doctor-doom-russo-brothers-avengers-doomsday-1236024107/' }
    ],
    seoTitle: 'Avengers: Doomsday (2026) | Robert Downey Jr. Doctor Doom & Cast News',
    seoDescription: 'Verified intelligence, casting reveals, production schedules, and plot breakdowns for Avengers: Doomsday directed by the Russo Brothers.'
  },
  {
    title: 'Avengers: Secret Wars',
    slug: 'avengers-secret-wars',
    description: 'The monumental culmination of the Multiverse Saga. Realities collide in a cataclysmic multiversal incursion, forging the patchwork battleground of Battleworld under the tyrannical dominion of God Emperor Doom.',
    status: 'ANNOUNCED',
    releaseDate: 'May 7, 2027',
    heroImage: 'https://images.unsplash.com/photo-1514533450685-4493e01d1fdc?q=80&w=1600&auto=format&fit=crop',
    heroImageAlt: 'Fractured crystalline cosmic nexus where divergent starfields and reality shards collide',
    poster: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?q=80&w=600&auto=format&fit=crop',
    genres: ['Action', 'Sci-Fi', 'Fantasy'],
    tags: ['Secret Wars', 'Battleworld', 'God Emperor Doom', 'Multiverse Culmination'],
    characters: ['doctor-doom', 'mr-fantastic', 'spider-man', 'wolverine', 'deadpool', 'thor', 'loki', 'doctor-strange', 'scarlet-witch', 'professor-x', 'magneto'],
    actors: ['Robert Downey Jr.', 'Pedro Pascal', 'Tom Holland', 'Hugh Jackman', 'Ryan Reynolds', 'Chris Hemsworth', 'Tom Hiddleston', 'Benedict Cumberbatch', 'Elizabeth Olsen'],
    featured: true,
    director: 'Anthony Russo & Joe Russo',
    writers: ['Stephen McFeely'],
    producers: ['Kevin Feige', 'Anthony Russo', 'Joe Russo'],
    universe: 'Battleworld / Multiverse',
    timeline: 'Phase 6 Grand Finale',
    synopsis: 'Following the total incursion and destruction of the multiverse, God Emperor Doom rules over Battleworld—a fused, patchwork reality assembled from surviving domain fragments. A desperate rebellion led by Mister Fantastic, Spider-Man, Wolverine, and surviving Avengers battles to overthrow Doom and resurrect the timeline.',
    officialSources: [
      { name: 'Marvel Studios', url: 'https://www.marvel.com/movies/avengers-secret-wars' },
      { name: 'Variety', url: 'https://variety.com/2024/film/news/avengers-secret-wars-russo-brothers-directing-1236087796/' }
    ],
    seoTitle: 'Avengers: Secret Wars (2027) | Multiverse Climax & Battleworld Dossier',
    seoDescription: 'The definitive intelligence hub for Avengers: Secret Wars, covering Battleworld rumors, legacy Marvel cameos, and the Russo Brothers\' production roadmap.'
  },
  {
    title: 'Ghost Rider',
    slug: 'ghost-rider',
    description: 'The Spirit of Vengeance returns to the cinematic screen as a darker, supernatural thriller exploring occult pacts, hellfire retribution, and the dawn of the Midnight Sons.',
    status: 'ANNOUNCED',
    releaseDate: 'Late 2027 / 2028',
    heroImage: 'https://images.unsplash.com/photo-1517849845537-4d257902454a?q=80&w=1600&auto=format&fit=crop',
    heroImageAlt: 'Incandescent sulfur hellfire roaring along an asphalt desert highway at midnight',
    poster: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?q=80&w=600&auto=format&fit=crop',
    genres: ['Horror', 'Action', 'Supernatural'],
    tags: ['Ghost Rider', 'Midnight Sons', 'Hellfire', 'Supernatural', 'Spirit of Vengeance'],
    characters: ['ghost-rider', 'blade', 'punisher'],
    actors: ['Ryan Gosling (In Discussions)'],
    featured: false,
    director: 'To Be Announced',
    writers: ['Creative Development Group'],
    producers: ['Kevin Feige'],
    universe: 'Earth-616',
    timeline: 'Supernatural Slate',
    synopsis: 'Bound by a blood-pact to an ancient demonic entity, Johnny Blaze roams the forgotten highways of the American Southwest, unleashing the Penance Stare against supernatural predation and corrupt earthly souls.',
    officialSources: [
      { name: 'Marvel Studios Development Ledger', url: 'https://www.marvel.com' },
      { name: 'MTV News Interview (Ryan Gosling)', url: 'https://variety.com/2022/film/news/ryan-gosling-ghost-rider-mcu-kevin-feige-1235323531/' }
    ],
    seoTitle: 'Ghost Rider MCU Movie | Ryan Gosling Rumors & Midnight Sons News',
    seoDescription: 'All verified updates, trade reports, and development status for Marvel Studios\' upcoming Ghost Rider project and supernatural slate.'
  },
  {
    title: 'Black Panther 3',
    slug: 'black-panther-3',
    description: 'Ryan Coogler returns to complete the visionary Wakanda trilogy, charting Wakanda\'s ascension on the world stage, the grooming of young Prince T\'Challa II, and ancestral conflict.',
    status: 'ANNOUNCED',
    releaseDate: '2028',
    heroImage: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=1600&auto=format&fit=crop',
    heroImageAlt: 'Golden sunrise sweeping across the futuristic vibranium towers and lush canopy of Birnin Zana',
    poster: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?q=80&w=600&auto=format&fit=crop',
    genres: ['Action', 'Drama', 'Sci-Fi'],
    tags: ['Wakanda', 'Black Panther', 'T\'Challa II', 'Ryan Coogler', 'Denzel Washington'],
    characters: ['black-panther-shuri', 'tchalla-ii', 'namor'],
    actors: ['Letitia Wright', 'David Jonsson', 'Tenoch Huerta Mejía', 'Denzel Washington'],
    featured: false,
    director: 'Ryan Coogler',
    writers: ['Ryan Coogler'],
    producers: ['Kevin Feige', 'Nate Moore'],
    universe: 'Earth-616',
    timeline: 'Post-Secret Wars',
    synopsis: 'As global superpowers intensify their covert efforts to plunder vibranium reserves, Queen Shuri must navigate geopolitical destabilization while preparing young T\'Challa II to inherit his father\'s sacred legacy.',
    officialSources: [
      { name: 'The Today Show (Denzel Washington Announcement)', url: 'https://variety.com/2024/film/news/denzel-washington-black-panther-3-ryan-coogler-1236208035/' }
    ],
    seoTitle: 'Black Panther 3 | Ryan Coogler, Denzel Washington & T\'Challa II Intel',
    seoDescription: 'Inside Black Panther 3: Denzel Washington role confirmation, David Jonsson rumors, and Wakanda\'s future in the Marvel Cinematic Universe.'
  },
  {
    title: 'X-Men',
    slug: 'x-men',
    description: 'Marvel Studios officially reboots the Children of the Atom for the Marvel Cinematic Universe, exploring mutant persecution, Cerebro school dynamics, and Xavier\'s peaceful coexistence dream.',
    status: 'ANNOUNCED',
    releaseDate: '2028',
    heroImage: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?q=80&w=1600&auto=format&fit=crop',
    heroImageAlt: 'Gothic stone arches and manicured lawns of Xavier\'s School for Gifted Youngsters in Westchester',
    poster: 'https://images.unsplash.com/photo-1563089145-599997674d42?q=80&w=600&auto=format&fit=crop',
    genres: ['Sci-Fi', 'Action', 'Drama'],
    tags: ['Mutants', 'X-Men', 'Xavier', 'Magneto', 'Post-Secret Wars'],
    characters: ['cyclops', 'jean-grey', 'storm', 'wolverine', 'rogue', 'professor-x', 'magneto', 'emma-frost', 'nightcrawler', 'beast'],
    actors: ['Ensemble Cast In Casting'],
    featured: true,
    director: 'Jake Schreier (In Talks)',
    writers: ['Michael Lesslie'],
    producers: ['Kevin Feige'],
    universe: 'Earth-616 (Mainline)',
    timeline: 'Post-Secret Wars Era',
    synopsis: 'Born with the genetic X-gene, mutants begin emerging in exponential numbers across the globe. Facing escalating human prejudice, Sentinel robotics surveillance, and militant mutant factions, Professor Charles Xavier gathers gifted young outcasts to forge the heroic vanguard known as the X-Men.',
    officialSources: [
      { name: 'Deadline (Michael Lesslie Script Announcement)', url: 'https://deadline.com/2024/05/x-men-movie-marvel-studios-michael-lesslie-1235926521/' }
    ],
    seoTitle: 'MCU X-Men Movie | Writer Michael Lesslie, Casting & Rumors',
    seoDescription: 'Everything we know about Marvel Studios\' live-action X-Men reboot: script progress, director contenders, and character roster breakdowns.'
  },
  {
    title: 'Blade',
    slug: 'blade',
    description: 'Academy Award-winner Mahershala Ali stars as the legendary Daywalker in a gritty, blood-soaked Gothic horror thriller exploring London\'s ancient vampire aristocracy.',
    status: 'PRE_PRODUCTION',
    releaseDate: '2026 / 2027',
    heroImage: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?q=80&w=1600&auto=format&fit=crop',
    heroImageAlt: 'Dark rain-soaked Gothic cathedral gargoyles overlooking foggy Victorian London alleys',
    poster: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=600&auto=format&fit=crop',
    genres: ['Horror', 'Action', 'Fantasy'],
    tags: ['Blade', 'Daywalker', 'Midnight Sons', 'Vampires', 'Mahershala Ali'],
    characters: ['blade', 'ghost-rider'],
    actors: ['Mahershala Ali', 'Mia Goth'],
    featured: false,
    director: 'In Director Search',
    writers: ['Eric Pearson'],
    producers: ['Kevin Feige'],
    universe: 'Earth-616',
    timeline: 'Phase 6 Supernatural',
    synopsis: 'Born half-human and half-vampire, Eric Brooks dedicates his existence to eradicating the blood-drinking fiends that stalk humanity. When a clandestine aristocratic vampire clan attempts to trigger eternal darkness, Blade must unsheathe his silver sword.',
    officialSources: [
      { name: 'Marvel.com Blade Announcement', url: 'https://www.marvel.com/movies/blade' },
      { name: 'The Hollywood Reporter (Production Updates)', url: 'https://www.hollywoodreporter.com/movies/movie-news/blade-delays-marvel-studios-1235921000/' }
    ],
    seoTitle: 'Blade (MCU) | Mahershala Ali, Production Updates & Release Intel',
    seoDescription: 'Complete development timeline and status updates on Marvel Studios\' Blade starring Mahershala Ali and Mia Goth.'
  },
  {
    title: 'Avengers: Endgame',
    slug: 'avengers-endgame',
    description: 'The monumental culmination of twenty-two films. The remaining Avengers undertake the desperate Time Heist through the Quantum Realm to reverse Thanos\'s snap and restore the universe.',
    status: 'RELEASED',
    releaseDate: 'April 26, 2019',
    heroImage: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?q=80&w=1600&auto=format&fit=crop',
    heroImageAlt: 'Shattered compound crater where all assembled Avengers stand shoulder to shoulder',
    poster: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=600&auto=format&fit=crop',
    genres: ['Action', 'Sci-Fi', 'Drama'],
    tags: ['Infinity Saga Finale', 'Time Heist', 'Thanos', 'Iron Man', 'Captain America'],
    characters: ['steve-rogers', 'thor', 'hulk', 'ant-man', 'spider-man', 'bucky-barnes', 'loki'],
    actors: ['Robert Downey Jr.', 'Chris Evans', 'Mark Ruffalo', 'Chris Hemsworth', 'Scarlett Johansson', 'Jeremy Renner', 'Paul Rudd'],
    featured: false,
    director: 'Anthony Russo & Joe Russo',
    writers: ['Christopher Markus', 'Stephen McFeely'],
    producers: ['Kevin Feige'],
    universe: 'Earth-616',
    timeline: 'Infinity Saga Finale',
    synopsis: 'After the devastating events of Infinity War, the universe is in ruins. With the help of remaining allies, the Avengers assemble once more to reverse Thanos\'s actions and restore balance to the universe.',
    officialSources: [
      { name: 'Box Office Mojo ($2.799B All-Time)', url: 'https://www.boxofficemojo.com/title/tt4154796/' }
    ],
    seoTitle: 'Avengers: Endgame | Box Office Records, Synopsis & MCU Legacy',
    seoDescription: 'Production archives and box office retrospective for Avengers: Endgame, directed by Anthony and Joe Russo.'
  },
  {
    title: 'Avengers: Infinity War',
    slug: 'avengers-infinity-war',
    description: 'The Avengers and their allies must be willing to sacrifice all in an attempt to defeat the powerful Thanos before his blitz of devastation and ruin puts an end to the universe.',
    status: 'RELEASED',
    releaseDate: 'April 27, 2018',
    heroImage: 'https://images.unsplash.com/photo-1514533450685-4493e01d1fdc?q=80&w=1600&auto=format&fit=crop',
    heroImageAlt: 'Titan ruins and disintegrating planetary fragments under fiery orange solar flare',
    poster: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?q=80&w=600&auto=format&fit=crop',
    genres: ['Action', 'Sci-Fi', 'Adventure'],
    tags: ['Infinity War', 'Thanos', 'Infinity Stones', 'The Snap'],
    characters: ['thor', 'doctor-strange', 'spider-man', 'steve-rogers', 'hulk', 'scarlet-witch', 'loki'],
    actors: ['Josh Brolin', 'Robert Downey Jr.', 'Chris Hemsworth', 'Benedict Cumberbatch', 'Tom Holland', 'Chris Evans'],
    featured: false,
    director: 'Anthony Russo & Joe Russo',
    writers: ['Christopher Markus', 'Stephen McFeely'],
    producers: ['Kevin Feige'],
    universe: 'Earth-616',
    timeline: 'Infinity Saga Act III',
    synopsis: 'Thanos embarks on a relentless conquest across space to gather all six Infinity Stones. Earth\'s mightiest heroes clash with the Black Order across New York, Edinburgh, Knowhere, Titan, and Wakanda in a tragic standoff that ends with the snap.',
    officialSources: [
      { name: 'Marvel.com', url: 'https://www.marvel.com/movies/avengers-infinity-war' }
    ],
    seoTitle: 'Avengers: Infinity War | Complete MCU Retrospective Dossier',
    seoDescription: 'Detailed archive on Avengers: Infinity War, documenting the arrival of Thanos and the Infinity Gauntlet storyline.'
  },
  {
    title: 'Spider-Man: No Way Home',
    slug: 'spiderman-no-way-home',
    description: 'With Spider-Man\'s identity revealed, Peter enlists Doctor Strange\'s help to restore his secret, inadvertently rupturing the multiverse and unleashing villains from across cinematic history.',
    status: 'RELEASED',
    releaseDate: 'December 17, 2021',
    heroImage: 'https://images.unsplash.com/photo-1635805737707-575885ab0820?q=80&w=1600&auto=format&fit=crop',
    heroImageAlt: 'Statue of Liberty scaffold surrounded by mystical orange spell rings and multiversal purple sky tears',
    poster: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=600&auto=format&fit=crop',
    genres: ['Action', 'Adventure', 'Sci-Fi'],
    tags: ['Spider-Verse', 'Multiverse', 'Tobey Maguire', 'Andrew Garfield', 'Green Goblin'],
    characters: ['spider-man', 'doctor-strange', 'daredevil'],
    actors: ['Tom Holland', 'Zendaya', 'Benedict Cumberbatch', 'Tobey Maguire', 'Andrew Garfield', 'Willem Dafoe', 'Alfred Molina'],
    featured: false,
    director: 'Jon Watts',
    writers: ['Chris McKenna', 'Erik Sommers'],
    producers: ['Kevin Feige', 'Amy Pascal'],
    universe: 'Earth-616 / Sony Multiverse',
    timeline: 'Phase 4 Multiverse Launch',
    synopsis: 'Peter Parker\'s life is upended when Mysterio exposes his identity. Seeking a mystical solution from Doctor Strange, the spell goes awry, pulling Green Goblin, Doc Ock, Electro, Sandman, Lizard, and two alternate Peter Parkers into his world.',
    officialSources: [
      { name: 'Box Office Mojo ($1.921B Global)', url: 'https://www.boxofficemojo.com/title/tt10872600/' }
    ],
    seoTitle: 'Spider-Man: No Way Home | Box Office, 3 Spiders & Multiverse Impact',
    seoDescription: 'Historical record of Spider-Man: No Way Home, covering the historic uniting of Tom Holland, Tobey Maguire, and Andrew Garfield.'
  },
  {
    title: 'Deadpool & Wolverine',
    slug: 'deadpool-and-wolverine',
    description: 'A listless Wade Wilson is pulled into the Time Variance Authority, teaming up with a haunted, reluctant Wolverine on an R-rated multiversal mission to save his dying universe.',
    status: 'RELEASED',
    releaseDate: 'July 26, 2024',
    heroImage: 'https://images.unsplash.com/photo-1563089145-599997674d42?q=80&w=1600&auto=format&fit=crop',
    heroImageAlt: 'Yellow and blue spandex tactical suit standing beside red and black masked combatant in desolate wasteland',
    poster: 'https://images.unsplash.com/photo-1635805737707-575885ab0820?q=80&w=600&auto=format&fit=crop',
    genres: ['Action', 'Comedy', 'Sci-Fi'],
    tags: ['Deadpool', 'Wolverine', 'TVA', 'The Void', 'R-Rated Box Office Record'],
    characters: ['deadpool', 'wolverine', 'gambit', 'human-torch'],
    actors: ['Ryan Reynolds', 'Hugh Jackman', 'Emma Corrin', 'Channing Tatum', 'Chris Evans', 'Wesley Snipes'],
    featured: true,
    director: 'Shawn Levy',
    writers: ['Ryan Reynolds', 'Rhett Reese', 'Paul Wernick', 'Zeb Wells', 'Shawn Levy'],
    producers: ['Kevin Feige', 'Ryan Reynolds', 'Shawn Levy', 'Lauren Shuler Donner'],
    universe: 'Earth-10005 / The Void / Earth-616',
    timeline: 'Phase 5 Box Office Juggernaut',
    synopsis: 'Six years after Deadpool 2, Wade Wilson works as a used car salesman. Captured by rogue TVA agent Paradox, Wade learns his reality is deteriorating due to the loss of anchor being Logan. Wade scours the multiverse for a variant Wolverine, plunging into the Void to face Cassandra Nova.',
    officialSources: [
      { name: 'Box Office Mojo ($1.338B - #1 R-Rated Film in History)', url: 'https://www.boxofficemojo.com/title/tt6263850/' }
    ],
    seoTitle: 'Deadpool & Wolverine | R-Rated Box Office Records & Void Cameos',
    seoDescription: 'Comprehensive dossier on Deadpool & Wolverine: box office milestones, Hugh Jackman\'s return, and multiversal implications for Phase 6.'
  },
  {
    title: 'Captain America: Brave New World',
    slug: 'captain-america-brave-new-world',
    description: 'Sam Wilson finds himself in the middle of an international incident after meeting with newly elected U.S. President Thaddeus Ross, uncovering a nefarious global plot that unleashes Red Hulk.',
    status: 'POST_PRODUCTION',
    releaseDate: 'February 14, 2025',
    heroImage: 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?q=80&w=1600&auto=format&fit=crop',
    heroImageAlt: 'White House press podium flanked by American flags and military security details',
    poster: 'https://images.unsplash.com/photo-1569003339405-ea396a5a8a90?q=80&w=600&auto=format&fit=crop',
    genres: ['Action', 'Political Thriller', 'Sci-Fi'],
    tags: ['Captain America', 'Sam Wilson', 'Red Hulk', 'Adamantium', 'The Leader'],
    characters: ['captain-america-sam-wilson', 'hulk', 'bucky-barnes'],
    actors: ['Anthony Mackie', 'Harrison Ford', 'Danny Ramirez', 'Shira Haas', 'Giancarlo Esposito', 'Tim Blake Nelson'],
    featured: false,
    director: 'Julius Onah',
    writers: ['Malcolm Spellman', 'Dalan Musson', 'Matthew Orton'],
    producers: ['Kevin Feige', 'Nate Moore'],
    universe: 'Earth-616',
    timeline: 'Phase 5 Theatrical Climax',
    synopsis: 'Newly inaugurated President Thaddeus "Thunderbolt" Ross recruits Sam Wilson to reform the Avengers. However, an assassination attempt reveals an insidious conspiracy linked to the emergence of adamantium from Tiamut\'s oceanic corpse.',
    officialSources: [
      { name: 'Marvel Studios Official Trailer', url: 'https://www.marvel.com/movies/captain-america-brave-new-world' }
    ],
    seoTitle: 'Captain America: Brave New World | Red Hulk, Harrison Ford & Intel',
    seoDescription: 'Complete intelligence file on Captain America: Brave New World starring Anthony Mackie and Harrison Ford as President Ross / Red Hulk.'
  },
  {
    title: 'Thunderbolts*',
    slug: 'thunderbolts',
    description: 'An irreverent team-up featuring depressed assassin Yelena Belova, Bucky Barnes, and the MCU\'s least-anticipated band of misfit antiheroes executing black-ops missions for Valentina Allegra de Fontaine.',
    status: 'POST_PRODUCTION',
    releaseDate: 'May 2, 2025',
    heroImage: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?q=80&w=1600&auto=format&fit=crop',
    heroImageAlt: 'Covert subterranean bunker command center with weapons crates and classified tactical maps',
    poster: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?q=80&w=600&auto=format&fit=crop',
    genres: ['Action', 'Thriller', 'Comedy'],
    tags: ['Thunderbolts', 'Yelena Belova', 'Bucky Barnes', 'Sentry', 'Black Ops'],
    characters: ['yelena-belova', 'bucky-barnes'],
    actors: ['Florence Pugh', 'Sebastian Stan', 'David Harbour', 'Wyatt Russell', 'Olga Kurylenko', 'Hannah John-Kamen', 'Julia Louis-Dreyfus', 'Lewis Pullman'],
    featured: true,
    director: 'Jake Schreier',
    writers: ['Eric Pearson', 'Lee Sung Jin', 'Joanna Calo'],
    producers: ['Kevin Feige'],
    universe: 'Earth-616',
    timeline: 'Phase 5 Finale',
    synopsis: 'Brought together on a covert assassination mission that turns out to be a lethal corporate trap, Yelena Belova, Bucky Barnes, Red Guardian, U.S. Agent, Ghost, and Taskmaster discover a mysterious subject named "Bob" possessing unfathomable solar-charged power.',
    officialSources: [
      { name: 'Marvel Studios Official Teaser', url: 'https://www.marvel.com/movies/thunderbolts' }
    ],
    seoTitle: 'Thunderbolts* (2025) | Yelena Belova, Sentry & Asterisk Mystery',
    seoDescription: 'Inside Marvel Studios\' Thunderbolts*: trailer breakdowns, Lewis Pullman as Sentry, and the covert narrative bridge to Avengers: Doomsday.'
  },
  {
    title: 'Doctor Strange in the Multiverse of Madness',
    slug: 'doctor-strange-multiverse-of-madness',
    description: 'Doctor Strange teams with mysterious multiverse-hopping teenager America Chavez to traverse perilous alternate realities, fleeing a corrupted, grief-stricken Scarlet Witch.',
    status: 'RELEASED',
    releaseDate: 'May 6, 2022',
    heroImage: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=1600&auto=format&fit=crop',
    heroImageAlt: 'Fractured glass shards reflecting demonic red runes and eldritch sorcery',
    poster: 'https://images.unsplash.com/photo-1514533450685-4493e01d1fdc?q=80&w=600&auto=format&fit=crop',
    genres: ['Fantasy', 'Action', 'Horror'],
    tags: ['Multiverse', 'Darkhold', 'Illuminati', 'Sam Raimi', 'Incursions'],
    characters: ['doctor-strange', 'scarlet-witch', 'mr-fantastic', 'professor-x'],
    actors: ['Benedict Cumberbatch', 'Elizabeth Olsen', 'Chiwetel Ejiofor', 'Benedict Wong', 'Xochitl Gomez', 'Rachel McAdams'],
    featured: false,
    director: 'Sam Raimi',
    writers: ['Michael Waldron'],
    producers: ['Kevin Feige'],
    universe: 'Earth-616 / Earth-838 / Gap Junction',
    timeline: 'Phase 4 Incursion Setup',
    synopsis: 'Traversing the bizarre dimensions of the multiverse, Doctor Strange confronts sinister alternate variants of himself while seeking to protect America Chavez from the Darkhold-corrupted Wanda Maximoff, leading to the destruction of the Earth-838 Illuminati.',
    officialSources: [
      { name: 'Box Office Mojo ($955M Global)', url: 'https://www.boxofficemojo.com/title/tt9419884/' }
    ],
    seoTitle: 'Doctor Strange in the Multiverse of Madness | Incursion Lore & Illuminati',
    seoDescription: 'Archival report on Doctor Strange in the Multiverse of Madness: Illuminati cameos, Darkhold fallout, and universal incursion foundations.'
  },
  {
    title: 'Black Panther',
    slug: 'black-panther',
    description: 'T\'Challa returns home to the technologically advanced, isolated African nation of Wakanda to serve as its new king, confronting charismatic challenger Erik Killmonger.',
    status: 'RELEASED',
    releaseDate: 'February 16, 2018',
    heroImage: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=1600&auto=format&fit=crop',
    heroImageAlt: 'Panther statue overlooking the vibrant waterfalls of Warrior Falls in Wakanda',
    poster: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?q=80&w=600&auto=format&fit=crop',
    genres: ['Action', 'Adventure', 'Sci-Fi'],
    tags: ['Wakanda', 'T\'Challa', 'Killmonger', 'Vibranium', 'Oscar Winner'],
    characters: ['black-panther-shuri'],
    actors: ['Chadwick Boseman', 'Michael B. Jordan', 'Lupita Nyong\'o', 'Danai Gurira', 'Martin Freeman', 'Daniel Kaluuya', 'Letitia Wright', 'Angela Bassett', 'Forest Whitaker'],
    featured: false,
    director: 'Ryan Coogler',
    writers: ['Ryan Coogler', 'Joe Robert Cole'],
    producers: ['Kevin Feige'],
    universe: 'Earth-616',
    timeline: 'Phase 3 Cultural Phenomenon',
    synopsis: 'Following the death of King T\'Chaka, T\'Challa is crowned King of Wakanda. His sovereignty is tested when American black-ops operative Erik Stevens (Killmonger) arrives to claim the throne and export vibranium weapons to start a global revolution.',
    officialSources: [
      { name: 'Box Office Mojo ($1.349B - Best Picture Nominee)', url: 'https://www.boxofficemojo.com/title/tt1825683/' }
    ],
    seoTitle: 'Black Panther (2018) | Historic Cultural Milestone & Box Office Archive',
    seoDescription: 'Retrospective dossier on Ryan Coogler\'s Black Panther starring Chadwick Boseman: awards, cultural impact, and box office milestones.'
  },
  {
    title: 'Black Panther: Wakanda Forever',
    slug: 'black-panther-wakanda-forever',
    description: 'Grieving the untimely death of King T\'Challa, the leaders of Wakanda fight to protect their nation from invading world powers and the hidden undersea civilization of Talokan.',
    status: 'RELEASED',
    releaseDate: 'November 11, 2022',
    heroImage: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?q=80&w=1600&auto=format&fit=crop',
    heroImageAlt: 'White funeral shroud garments floating above the misty ocean horizon at twilight',
    poster: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=600&auto=format&fit=crop',
    genres: ['Action', 'Drama', 'Sci-Fi'],
    tags: ['Wakanda Forever', 'Shuri', 'Namor', 'Talokan', 'T\'Challa II'],
    characters: ['black-panther-shuri', 'namor', 'tchalla-ii'],
    actors: ['Letitia Wright', 'Lupita Nyong\'o', 'Danai Gurira', 'Winston Duke', 'Florence Kasumba', 'Dominique Thorne', 'Michaela Coel', 'Tenoch Huerta Mejía', 'Angela Bassett'],
    featured: false,
    director: 'Ryan Coogler',
    writers: ['Ryan Coogler', 'Joe Robert Cole'],
    producers: ['Kevin Feige', 'Nate Moore'],
    universe: 'Earth-616',
    timeline: 'Phase 4 Grand Finale',
    synopsis: 'Queen Ramonda, Shuri, M\'Baku, Okoye, and the Dora Milaje fight to protect their nation from intervening world powers in the wake of King T\'Challa\'s death. When CIA vibranium detectors pinpoint undersea reserves, Namor leads the aquatic kingdom of Talokan to war.',
    officialSources: [
      { name: 'Box Office Mojo ($859M Global)', url: 'https://www.boxofficemojo.com/title/tt9114286/' }
    ],
    seoTitle: 'Black Panther: Wakanda Forever | Shuri, Namor & Post-Credit Prince Dossier',
    seoDescription: 'In-depth archive of Black Panther: Wakanda Forever, detailing Shuri\'s ascension, the debut of Namor, and the introduction of T\'Challa II.'
  },
  {
    title: 'Loki',
    slug: 'loki',
    description: 'The mercurial God of Mischief is brought before the bureaucratic Time Variance Authority, uncovering the secrets of the Sacred Timeline and evolving into the God of Stories.',
    status: 'RELEASED',
    releaseDate: 'June 9, 2021',
    heroImage: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=1600&auto=format&fit=crop',
    heroImageAlt: 'Infinite green temporal strands woven into a luminous multiversal world tree at the End of Time',
    poster: 'https://images.unsplash.com/photo-1514533450685-4493e01d1fdc?q=80&w=600&auto=format&fit=crop',
    genres: ['Sci-Fi', 'Fantasy', 'Adventure'],
    tags: ['TVA', 'Time Slipping', 'God of Stories', 'He Who Remains', 'Yggdrasil'],
    characters: ['loki'],
    actors: ['Tom Hiddleston', 'Owen Wilson', 'Sophia Di Martino', 'Gugu Mbatha-Raw', 'Wunmi Mosaku', 'Jonathan Majors', 'Ke Huy Quan'],
    featured: false,
    director: 'Kate Herron / Justin Benson & Aaron Moorhead',
    writers: ['Michael Waldron', 'Eric Martin'],
    producers: ['Kevin Feige', 'Tom Hiddleston'],
    universe: 'TVA / End of Time / Multiverse',
    timeline: 'Multiverse Anchor Point',
    synopsis: 'After stealing the Tesseract during the Avengers\' time heist, an alternate Loki is apprehended by the Time Variance Authority. Across two acclaimed seasons, Loki uncovers the origins of He Who Remains, masters time-slipping, and sacrifices his freedom to hold the multiverse together as the God of Stories.',
    officialSources: [
      { name: 'Marvel.com Loki Dossier', url: 'https://www.marvel.com/tv-shows/loki' }
    ],
    seoTitle: 'Loki Season 1 & 2 | God of Stories, TVA Lore & Multiverse Anchor',
    seoDescription: 'Complete intelligence dossier on Marvel Studios\' Loki: time-slipping, Yggdrasil, and the temporal foundations of Avengers: Doomsday.'
  },
  {
    title: 'WandaVision',
    slug: 'wandavision',
    description: 'Living idealized suburban lives in the town of Westview, Wanda Maximoff and Vision begin to suspect that their classic sitcom reality is not what it seems, awakening the Scarlet Witch.',
    status: 'RELEASED',
    releaseDate: 'January 15, 2021',
    heroImage: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=1600&auto=format&fit=crop',
    heroImageAlt: 'Vintage retro cathode tube television screen flickering with crimson static hex patterns',
    poster: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=600&auto=format&fit=crop',
    genres: ['Mystery', 'Sci-Fi', 'Drama'],
    tags: ['Westview', 'Scarlet Witch', 'White Vision', 'Agatha Harkness', 'Chaos Magic'],
    characters: ['scarlet-witch', 'vision'],
    actors: ['Elizabeth Olsen', 'Paul Bettany', 'Kathryn Hahn', 'Teyonah Parris', 'Randall Park', 'Kat Dennings'],
    featured: false,
    director: 'Matt Shakman',
    writers: ['Jac Schaeffer'],
    producers: ['Kevin Feige'],
    universe: 'Earth-616',
    timeline: 'Phase 4 Television Benchmark',
    synopsis: 'Overcome with grief following Vision\'s death in Infinity War, Wanda Maximoff inadvertently casts a massive Chaos Magic hex over Westview, New Jersey. As S.W.O.R.D. and ancient witch Agatha Harkness probe the perimeter, Wanda awakens her full mythological potential as the Scarlet Witch.',
    officialSources: [
      { name: 'Emmys.com (23 Nominations)', url: 'https://www.emmys.com/shows/wandavision' }
    ],
    seoTitle: 'WandaVision | Scarlet Witch Hex, White Vision & MCU Phase 4 Legacy',
    seoDescription: 'Archival report on WandaVision: Emmy awards, Matt Shakman\'s direction, White Vision resurrection, and Scarlet Witch lore.'
  },
  {
    title: 'What If...?',
    slug: 'what-if',
    description: 'The Watcher observes the vast, uncharted multiverse, exploring pivotal alternate realities where single decisions altered the fate of iconic Marvel heroes and villains.',
    status: 'RELEASED',
    releaseDate: 'August 11, 2021',
    heroImage: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?q=80&w=1600&auto=format&fit=crop',
    heroImageAlt: 'Cosmic celestial eye of Uatu the Watcher reflecting prismatic infinite timeline branches',
    poster: 'https://images.unsplash.com/photo-1514533450685-4493e01d1fdc?q=80&w=600&auto=format&fit=crop',
    genres: ['Animation', 'Sci-Fi', 'Anthology'],
    tags: ['The Watcher', 'Multiverse Variants', 'Captain Carter', 'Infinity Ultron'],
    characters: ['ultron', 'doctor-strange'],
    actors: ['Jeffrey Wright', 'Hayley Atwell', 'Benedict Cumberbatch', 'Lake Bell', 'Mick Wingert'],
    featured: false,
    director: 'Bryan Andrews',
    writers: ['A.C. Bradley', 'Matthew Chauncey'],
    producers: ['Kevin Feige', 'Brad Winderbaum'],
    universe: 'Infinite Multiverse Domains',
    timeline: 'Multiverse Anthology',
    synopsis: 'Across three seasons, Uatu the Watcher guides audiences through parallel realities: from Peggy Carter taking the Super Soldier serum to Infinity Ultron acquiring all six Infinity Stones and threatening the cosmic fabric of all existence.',
    officialSources: [
      { name: 'Marvel Studios Animation', url: 'https://www.marvel.com/tv-shows/what-if' }
    ],
    seoTitle: 'What If...? (Animated Anthology) | Multiverse Variants & The Watcher',
    seoDescription: 'Complete series overview of Marvel Studios\' What If...? covering Infinity Ultron, Captain Carter, and multiversal concepts.'
  },
  {
    title: 'Shang-Chi and the Legend of the Ten Rings',
    slug: 'shang-chi',
    description: 'Shang-Chi must confront the criminal empire of his estranged immortal father Wenwu and unlock the ancestral martial magic of Ta Lo.',
    status: 'RELEASED',
    releaseDate: 'September 3, 2021',
    heroImage: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=1600&auto=format&fit=crop',
    heroImageAlt: 'San Francisco city bus interior shattered during high-speed kinetic martial arts duel',
    poster: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?q=80&w=600&auto=format&fit=crop',
    genres: ['Action', 'Fantasy', 'Adventure'],
    tags: ['Ten Rings', 'Ta Lo', 'Martial Arts', 'Destin Daniel Cretton'],
    characters: ['shang-chi'],
    actors: ['Simu Liu', 'Tony Leung', 'Awkwafina', 'Meng\'er Zhang', 'Fala Chen', 'Michelle Yeoh'],
    featured: false,
    director: 'Destin Daniel Cretton',
    writers: ['Dave Callaham', 'Destin Daniel Cretton', 'Andrew Lanham'],
    producers: ['Kevin Feige', 'Jonathan Schwartz'],
    universe: 'Earth-616',
    timeline: 'Phase 4 Origin Benchmark',
    synopsis: 'Living anonymously as a valet in San Francisco, Shang-Chi is ambushed by assassins seeking his dragon pendant. Reconnecting with his sister Xialing in Macau, he discovers his father Wenwu is being manipulated by the dark Dweller-in-the-Dark.',
    officialSources: [
      { name: 'Box Office Mojo ($432M Global)', url: 'https://www.boxofficemojo.com/title/tt9376612/' }
    ],
    seoTitle: 'Shang-Chi and the Legend of the Ten Rings | Martial Arts & Ten Rings Signal',
    seoDescription: 'Intelligence dossier on Shang-Chi: Destin Daniel Cretton\'s martial arts masterwork and the cosmic mystery of the Ten Rings beacon.'
  },
  {
    title: 'Daredevil: Born Again',
    slug: 'daredevil-born-again',
    description: 'Matt Murdock and Wilson Fisk attempt to put their costumed alter-egos behind them to serve New York City—one as a lawyer, the other as Mayor—until violent corruption collides on the streets.',
    status: 'POST_PRODUCTION',
    releaseDate: 'March 4, 2025',
    heroImage: 'https://images.unsplash.com/photo-1635805737707-575885ab0820?q=80&w=1600&auto=format&fit=crop',
    heroImageAlt: 'Hell\'s Kitchen brick fire escapes and neon diner signs reflected in wet nighttime streets',
    poster: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?q=80&w=600&auto=format&fit=crop',
    genres: ['Crime', 'Action', 'Drama'],
    tags: ['Daredevil', 'Kingpin', 'Born Again', 'Punisher', 'Street Level'],
    characters: ['daredevil', 'punisher', 'tombstone'],
    actors: ['Charlie Cox', 'Vincent D\'Onofrio', 'Jon Bernthal', 'Deborah Ann Woll', 'Elden Henson', 'Margarita Levieva', 'Michael Gandolfini'],
    featured: true,
    director: 'Justin Benson & Aaron Moorhead',
    writers: ['Dario Scardapane'],
    producers: ['Kevin Feige', 'Brad Winderbaum'],
    universe: 'Earth-616',
    timeline: 'Phase 5 Television Climax',
    synopsis: 'Following Wilson Fisk\'s election as Mayor of New York City and his legislative crusade to ban masked vigilantes, Matt Murdock struggles to maintain justice strictly inside the courtroom. When rogue police squads and ruthless assassins strike, the Devil of Hell\'s Kitchen must take up his batons once more.',
    officialSources: [
      { name: 'Marvel.com Official Premiere Announcement', url: 'https://www.marvel.com/tv-shows/daredevil-born-again' },
      { name: 'The Hollywood Reporter (Creative Overhaul Report)', url: 'https://www.hollywoodreporter.com/tv/tv-news/daredevil-born-again-marvel-overhaul-1235614500/' }
    ],
    seoTitle: 'Daredevil: Born Again (2025) | Charlie Cox, Kingpin & Punisher Intel',
    seoDescription: 'Inside Daredevil: Born Again: creative overhaul details, Jon Bernthal\'s return as the Punisher, and the street-level NYC power struggle.'
  }
];

fs.mkdirSync(moviesDir, { recursive: true });

for (const movie of moviesData) {
  const filePath = path.join(moviesDir, `${movie.slug}.json`);
  fs.writeFileSync(filePath, JSON.stringify(movie, null, 2), 'utf-8');
}

console.log(`Successfully generated ${moviesData.length} movie ledger files.`);
